name: Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  code-check:
    name: Check Go formatting, linting, vetting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2     
      - name: Run the formatter, linter, and vetter
        uses: dell/common-github-actions/go-code-formatter-linter-vetter@main
        with:
          directories: ./...
  test:
    name: Run Go unit tests and check package coverage
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: Force Install GIT latest
        run: |
          apt-get update
          apt-get install -y git
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Clone gopowerstore repository
        uses: actions/checkout@v2
        with:
          repository: dell/gopowermax
          path: gopowermax
          ref: main
      - name: See dir
        run: ls
      - name: Run unit tests and check package coverage
        uses: dell/common-github-actions/go-code-tester@main
        with:
          threshold: 90
          test-folder: "service"
        env:
          # The hostname used to communicate with the Redis service container
          REDIS_HOST: redis
          # The default Redis port
          REDIS_PORT: 6379
  go_security_scan:
    name: Go security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run Go Security
        uses: securego/gosec@master
        with:
          args: -exclude=G108,G402 -exclude-dir=csireverseproxy ./...
  malware_security_scan:
    name: Malware Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run malware scan
        uses: dell/common-github-actions/malware-scanner@main
        with:
          directories: .
          options: -ri
